[package]
name = "safe_en"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name= "save_big_data"
path = "examples/save_big_data.rs"

[[example]]
name= "load_big_data"
path = "examples/load_big_data.rs"

[dependencies]
chrono = "0.4.19"
reqwest = "0.10.0"

[dev-dependencies]
menemen = "1.0.0"
serde_json = "1.0"
prettytable-rs = "0.8.0"